services:
  backend:
    build:
      context: ./Comms-Server
      target: dev
    ports:
      - "${BACKEND_PORT:-5177}:8080"
    volumes:
      - ./Comms-Server:/src
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  postgres:
    ports:
      - "${DATABASE_PORT}:5432"
    
  seq:
    ports:
      - "5341:80"
    environment:
      SEQ_FIRSTRUN_NOAUTHENTICATION: true
