services:
  postgres:
    image: postgres:16
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    volumes:
      - comms_postgres_data:/var/lib/postgresql/data

  backend:
    build: ./Comms-Server
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: "Host=postgres;Database=${DATABASE_NAME};Username=${DATABASE_USER};Password=${DATABASE_PASSWORD};Port=5432"
      Jwt__Key: ${JWT_KEY}
    depends_on:
      - postgres

  frontend:
    build: ./Comms-Client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  comms_postgres_data:
